
development:
  adapter: postgresql
  encoding: unicode
  database: Play-Periodically_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: Play-Periodically_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: Play-Periodically_production
  pool: 5
